# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complexmessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omplexmessage.proto\x12\x07\x63omplex\"\xef\x04\n\x0e\x43omplexMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12/\n\x03sub\x18\x02 \x01(\x0b\x32\".complex.ComplexMessage.SubMessage\x12.\n\x04type\x18\x03 \x01(\x0e\x32 .complex.ComplexMessage.EnumType\x12\x0f\n\x07numbers\x18\x04 \x03(\x05\x12\x37\n\x08mappings\x18\x05 \x03(\x0b\x32%.complex.ComplexMessage.MappingsEntry\x1a\x9d\x02\n\nSubMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x39\n\x05state\x18\x04 \x01(\x0e\x32*.complex.ComplexMessage.SubMessage.SubEnum\x12\x41\n\x07\x64\x65tails\x18\x05 \x01(\x0b\x32\x30.complex.ComplexMessage.SubMessage.NestedMessage\x1a\x33\n\rNestedMessage\x12\x12\n\npercentage\x18\x01 \x01(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t\"-\n\x07SubEnum\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x46IRST\x10\x01\x12\n\n\x06SECOND\x10\x02\x1aS\n\rMappingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".complex.ComplexMessage.SubMessage:\x02\x38\x01\"1\n\x08\x45numType\x12\r\n\tUNDEFINED\x10\x00\x12\n\n\x06TYPE_A\x10\x01\x12\n\n\x06TYPE_B\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'complexmessage_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPLEXMESSAGE_MAPPINGSENTRY._options = None
  _COMPLEXMESSAGE_MAPPINGSENTRY._serialized_options = b'8\001'
  _globals['_COMPLEXMESSAGE']._serialized_start=34
  _globals['_COMPLEXMESSAGE']._serialized_end=657
  _globals['_COMPLEXMESSAGE_SUBMESSAGE']._serialized_start=236
  _globals['_COMPLEXMESSAGE_SUBMESSAGE']._serialized_end=521
  _globals['_COMPLEXMESSAGE_SUBMESSAGE_NESTEDMESSAGE']._serialized_start=423
  _globals['_COMPLEXMESSAGE_SUBMESSAGE_NESTEDMESSAGE']._serialized_end=474
  _globals['_COMPLEXMESSAGE_SUBMESSAGE_SUBENUM']._serialized_start=476
  _globals['_COMPLEXMESSAGE_SUBMESSAGE_SUBENUM']._serialized_end=521
  _globals['_COMPLEXMESSAGE_MAPPINGSENTRY']._serialized_start=523
  _globals['_COMPLEXMESSAGE_MAPPINGSENTRY']._serialized_end=606
  _globals['_COMPLEXMESSAGE_ENUMTYPE']._serialized_start=608
  _globals['_COMPLEXMESSAGE_ENUMTYPE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
