# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\x07\x65xample\"\x93\x01\n\x08\x45mployee\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12)\n\x05title\x18\x03 \x01(\x0e\x32\x1a.example.Employee.JobTitle\"B\n\x08JobTitle\x12\r\n\tUNDEFINED\x10\x00\x12\x0c\n\x08\x45NGINEER\x10\x01\x12\x0b\n\x07MANAGER\x10\x02\x12\x0c\n\x08\x44IRECTOR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPLOYEE']._serialized_start=28
  _globals['_EMPLOYEE']._serialized_end=175
  _globals['_EMPLOYEE_JOBTITLE']._serialized_start=109
  _globals['_EMPLOYEE_JOBTITLE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
