# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userprofile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userprofile.proto\x12\x07\x65xample\"\xf8\x01\n\x0bUserProfile\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12-\n\x07\x61\x64\x64ress\x18\x03 \x01(\x0b\x32\x1c.example.UserProfile.Address\x12.\n\x08\x63ontacts\x18\x04 \x03(\x0b\x32\x1c.example.UserProfile.Contact\x1a\x43\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x1a\'\n\x07\x43ontact\x12\r\n\x05phone\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userprofile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERPROFILE']._serialized_start=31
  _globals['_USERPROFILE']._serialized_end=279
  _globals['_USERPROFILE_ADDRESS']._serialized_start=171
  _globals['_USERPROFILE_ADDRESS']._serialized_end=238
  _globals['_USERPROFILE_CONTACT']._serialized_start=240
  _globals['_USERPROFILE_CONTACT']._serialized_end=279
# @@protoc_insertion_point(module_scope)
